#!/usr/bin/env node
'use strict';

const pug = require('pug');
const { MDArticleParser } = require('../lib/mdArticleParser');
const { readdir, writeFile } = require('fs').promises;
const fn = pug.compileFile('./includes/grep.pug');

run();

async function run() {
  let searchData = [];
  const files = await readdir('./posts');
  const postFiles = files.filter(f => /\.md$/.test(f));
  for (let post of postFiles) {
    let parser = new MDArticleParser({ path: `./posts/${post}` });
    parser.parse();
    searchData.push(parser.genSearch());
  }

  const grepHTML = fn({ searchData });
  await writeFile('./docs/grep.html', grepHTML);
  await writeFile('./search.json', JSON.stringify(searchData, null, 2));
}
