#!/usr/bin/env node
'use strict';

const { readFile, writeFile } = require('fs').promises;

run();

async function run() {
  let x = '';
  let t = await readFile('./Template.xml', 'utf-8');
  let jsonString = await readFile('./articles.json', 'utf-8');
  let articles = JSON.parse(jsonString);

  for (let article of articles) {
    x += `
<item>
<title>${article.title}</title>
<link>https://lineus.dev${article.link.replace(/^\./, '')}</link>
<guid>https://lineus.dev${article.link.replace(/^\//, '')}</guid>
<pubDate>${article.rssPublished}</pubDate>
<description>${article.rssSynopsis}</description>
</item>
    `;
  }

  await writeFile('./docs/articles.xml', t.replace(/\[articleSGOHERE\]/, x));
  return process.exit(0);
}
