#!/usr/bin/env node
'use strict';

const { readFile, writeFile } = require('fs').promises;

run();

async function run() {
  let x = '';
  let t = await readFile('./lineus.dev.xml', 'utf-8');
  let jsonString = await readFile('./posts.json', 'utf-8');
  let posts = JSON.parse(jsonString);

  for (let post of posts) {
    x += `
<item>
<title>${post.title}</title>
<link>https://lineus.dev${post.link.replace(/^\./, '')}</link>
<guid>https://lineus.dev${post.link.replace(/^\//, '')}</guid>
<pubDate>${post.rssPublished}</pubDate>
<description>${post.rssSynopsis}</description>
</item>
    `;
  }

  await writeFile('./docs/posts.xml', t.replace(/\[POSTSGOHERE\]/, x));
  return process.exit(0);
}
