#!/usr/bin/env node
'use strict';

const pug = require('pug');
const makeIndex = pug.compileFile('includes/index.pug');
const { writeFile } = require('fs').promises;

const indexOut = './docs/index.html';

run();

async function run() {
  const indexHTML = makeIndex({});
  await writeFile(indexOut, indexHTML);
}
