#!/usr/bin/env node
'use strict';

const pug = require('pug');
const fn = pug.compileFile('includes/pug/postTemplate.pug');
const makeLS = pug.compileFile('includes/pug/ls.pug');
const makeGrep = pug.compileFile('./includes/grep.pug');
const md = require('marked');
const { existsSync, promises } = require('fs');
const { readdir, readFile, writeFile } = promises;
const { MDArticle } = require('../lib/mdarticle');

const inDir = './posts/';
const outDir = './docs/posts/';
const lsOut = './docs/ls.html';

const ignoreIf = ['untitled', 'wip'];

run();

async function run() {
  const mdFiles = await getMDs(inDir);
  const files = [];
  const existingFiles = [];
  const searchData = [];
  let markPublished = false;
  for (let f of mdFiles) {
    let article = new MDArticle({ path: `${inDir}${f}`});
    article.parse();
    const e_p = !existsSync(article.file.fullPathOut) && article.isPublished();
    if (article.publishArticle() || article.updateArticle() || e_p) {
      searchData.push(article.genSearch());
      markPublished = article.publishArticle();
      if (markPublished) {
        article.markPublished();
      } else if (article.updateArticle()){
        article.markUpdated();
      }
      let file = {
        in: `${inDir}${f}`,
        out: `${outDir}${f.replace(/\.md$/, '.html')}`,
        link: `${outDir.replace('./docs/', '')}${f.replace(/\.md$/, '.html')}`,
        title: `${f.replace(/\.md$/, '').replace(/_/g, ' ')}`,
        published: new Date(article.data.published).toDateString(),
        updated: article.data.updated,
        synopsis: md(article.data.synopsis),
        rssPublished: new Date(article.data.published).toUTCString(),
        rssSynopsis: article.data.synopsis
      };
      files.push(file);
    } else if (article.isPublished()) {
      let file = {
        in: article.file.in,
        out: article.file.out,
        link: article.file.link,
        title: article.file.title,
        published: article.publishedOn(),
        updated: article.updatedOn(),
        synopsis: md(article.data.synopsis),
        rssPublished: new Date(article.data.published).toUTCString(),
        rssSynopsis: article.data.synopsis
      };
      existingFiles.push(file);
    }
  }

  for (let file of files) {
    await process(file);
  }

  const allFiles = files.concat(existingFiles);

  const grepHTML = makeGrep({ searchData });

  const lsHTML = makeLS({
    posts: allFiles.sort((a, b) => {
      let aD = new Date(a.published);
      let bD = new Date(b.published);
      return bD - aD;
    })
  });
  await writeFile(lsOut, lsHTML);
  await writeFile('./docs/grep.html', grepHTML);

  await writeFile('./posts.json', JSON.stringify(allFiles, null, 2));
  await writeFile('./search.json', JSON.stringify(searchData, null, 2));
}

async function getMDs(dir) {
  const files = await readdir(dir);
  return files
    .filter(f => /\.md$/.test(f))
    .filter(ignored);
}

function ignored(fileName) {
  let ret = true;
  for (let isIgnored of ignoreIf) {
    let re = new RegExp(`${isIgnored}`, 'i');
    if (re.test(fileName)) {
      ret = false;
    }
  }
  return ret;
}

async function process(file) {
  let contents = await readFile(file.in, 'utf-8');
  let blargh = fn({
    title: file.title,
    post: md(contents),
    postLink: file.out
  });
  let post = blargh.replace(/<!--.*-->/g, '');
  await writeFile(file.out, post);
}
